# Generated by Django 4.1.5 on 2023-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_product_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='is_default',
            field=models.BooleanField(default=False, help_text='format : true=subproduct visible', verbose_name='default selection'),
        ),
    ]
