# Generated by Django 4.1.5 on 2023-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_producttypeattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/categories/default.png', help_text='format : required , default-default.png', upload_to='images/categories/', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='images/products/default.png', help_text='format : required , default-default.png', upload_to='images/products/', verbose_name='product image'),
        ),
    ]
