# Generated by Django 4.1.5 on 2023-02-03 19:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_image_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='format : not required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category', verbose_name='parent of category'),
        ),
        migrations.AlterField(
            model_name='media',
            name='product_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_product_inventory', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='inventory.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='attributevalues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevaluess', to='inventory.productattributevalue'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='productinventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributevaluess', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type', to='inventory.producttype'),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattribute', to='inventory.productattribute'),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttype', to='inventory.producttype'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='inventory.productinventory'),
        ),
    ]
