# Generated by Django 4.1.5 on 2023-02-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_parent_alter_media_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product'),
        ),
    ]
