# Generated by Django 4.1.5 on 2023-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productinventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='is_default',
            field=models.BooleanField(default=False, help_text='format : true=select as default variant', verbose_name='default variant selection'),
        ),
    ]
