# Generated by Django 4.1.5 on 2023-02-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_productattributevalue_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalues',
            name='is_default',
        ),
    ]
